config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :courses
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'student_course', to: 'student_courses#create'
  delete 'student_course', to: 'student_courses#destroy'
  post 'change_grade', to: 'student_courses#change_grade'
  resources :teachers, only: [:new, :create, :edit, :update, :show]
  get '/teachers/:id/my_courses', to: 'teachers#my_courses', as: 'teacher_courses'
  get '/teachers/:id/my_students', to: 'teachers#my_students', as: 'teacher_students'
  get 'teacher_login', to: 'teacher_sessions#new'
  post 'teacher_login', to: 'teacher_sessions#create'
  delete 'teacher_logout', to: 'teacher_sessions#destroy'
end

app/controllers/teacher_sessions_controller.rb
class TeacherSessionsController < ApplicationController
  skip_before_action :require_user_or_teacher

  def new

  end

  def create
    teacher = Teacher.find_by(email: params[:teacher_sessions][:email])
    if teacher && teacher.authenticate(params[:teacher_sessions][:password])
      flash[:notice] = "You have successfully logged in as a teacher"
      session[:teacher_id] = teacher.id
      redirect_to teacher
    else
      render "new"
    end
  end

  def destroy
    session[:teacher_id] = nil
    flash[:notice] = "You have successfully logged out as a teacher"
    redirect_to teacher_login_path
  end

end

app/views/teacher_sessions/new.html.erb
<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header">Teacher's log in</h3>
        <div class="row">
          <%= form_for :teacher_sessions, html: {class: 'col s12'} do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter your email address", autofocus: true %>
                <%= f.label :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Enter your password" %>
                <%= f.label :password, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button '<i class="material-icons right">arrow_forward</i>Log in'.html_safe, class: "btn orange waves-effect waves-light right" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'Teacher\'s sign up page', new_teacher_path, class: "btn orange waves-effect waves-light right" %>
</div>