config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :courses
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'student_course', to: 'student_courses#create'
  delete 'student_course', to: 'student_courses#destroy'
  post 'change_grade', to: 'student_courses#change_grade'
  resources :teachers, only: [:new, :create, :edit, :update, :show]
  get '/teachers/:id/my_courses', to: 'teachers#my_courses', as: 'teacher_courses'
  get '/teachers/:id/my_students', to: 'teachers#my_students', as: 'teacher_students'
  get 'teacher_login', to: 'teacher_sessions#new'
  post 'teacher_login', to: 'teacher_sessions#create'
  delete 'teacher_logout', to: 'teacher_sessions#destroy'
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user_or_teacher, only: [:new, :create]
  before_action :set_student, only: [:show, :edit, :update]
  before_action :require_same_student, only: [:edit, :update]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "You have successfully signed up"
      redirect_to @student
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "You have successfully updated your profile"
      redirect_to @student
    else
      render 'edit'
    end
  end

  private

  def student_params
    params.require(:student).permit(:name,  :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student
    if current_user != @student
      flash[:notice] = "You can only edit your own profile"
      redirect_to student_path(current_user)
    end
  end

end

app/views/students/_form.html.erb
<%= render partial: 'shared/errors', locals: { obj: @student } %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @student.new_record? ? "Sign up!" : "Edit your profile!" %></h3>
        <div class="row">
          <%= form_for @student, html: {class: 'col s12'} do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                <%= f.label :name %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter your email address" %>
                <%= f.label :email, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Choose a password" %>
                <%= f.label :password, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: "Confirm your password" %>
                <%= f.label :password_confirmation, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@student.new_record? ? '<i class="material-icons right">arrow_forward</i>Sign up'.html_safe : '<i class="material-icons right">arrow_forward</i>Submit changes'.html_safe , class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Students Directory</h3>
  </div>
</div>

<div class="row">
  <% @students.each do |student| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= student.name %></span>
          <p>Email: <%= student.email %></p>
          <p>Course Enrollments: None</p>
        </div>
        <div class="card-action">
          <%= link_to "View Profile", student_path(student) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row">
  <div class="col s6 m6">
    <div class="card blue-grey darken-1 sign-up-form">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= @student.name %></span>
        <p>Email: <%= @student.email %></p>
        <br>
        <% if current_user == @student %>
          <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn-small" %>
        <% end %>
      </div>
    </div>
    <% if @student.courses.empty? %>
     <p>Course Enrollments: None</p>
    <% else %>
      <table>
        <thead>
          <tr>
            <th>Course Name</th>
            <th>Teacher Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @student.courses.each do |course| %>
          <tr>
            <td><%= course.name %></td>
            <td><%= course.teacher.formal_name %></td>
            <td><%= link_to 'Remove', student_course_path(course_id: course.id), method: :delete, class: 'waves-effect waves-light yellow darken-4 btn-small' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>