config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :courses
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'student_course', to: 'student_courses#create'
  delete 'student_course', to: 'student_courses#destroy'
  post 'change_grade', to: 'student_courses#change_grade'
  resources :teachers, only: [:new, :create, :edit, :update, :show]
  get '/teachers/:id/my_courses', to: 'teachers#my_courses', as: 'teacher_courses'
  get '/teachers/:id/my_students', to: 'teachers#my_students', as: 'teacher_students'
  get 'teacher_login', to: 'teacher_sessions#new'
  post 'teacher_login', to: 'teacher_sessions#create'
  delete 'teacher_logout', to: 'teacher_sessions#destroy'
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :name, presence: true, length: { in: 5..50 }
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_many :courses
  has_secure_password

  def formal_name
    self.position + " " + self.name
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  skip_before_action :require_user_or_teacher
  before_action :require_teacher
  before_action :set_teacher, only: [:edit, :update, :show, :my_courses, :my_students]
  before_action :require_same_teacher, only: [:edit, :update, :my_courses, :my_students]


  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_param)
    if @teacher.save
      flash[:notice] = "You have successfully signed up as a teacher"
      redirect_to @teacher
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @teacher.update(teacher_param)
      flash[:notice] = "You have successfully updated your profile"
      redirect_to @teacher
    else
      flash.now[:notice] = "You cannnot update your account because of incorrect information"
      render 'edit'
    end
  end

  def show
  end

  def my_courses
    @courses = @teacher.courses
  end

  def my_students
    @courses = @teacher.courses
  end


  private

  def teacher_param
    params.require(:teacher).permit(:name, :email, :position, :password, :password_confirmation)
  end

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def require_same_teacher
    if @teacher != current_teacher
      flash[:notice] = "You can update your profile only"
      redirect_to current_teacher
    end
  end

end

app/views/teachers/_form.html.erb
<%= render partial: 'shared/errors', locals: { obj: @teacher } %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @teacher.new_record? ? "Teacher's sign up!" : "Edit your profile!" %></h3>
        <div class="row">
          <%= form_for @teacher, html: {class: 'col s12'} do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                <%= f.label :name %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter your email address" %>
                <%= f.label :email, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.select :position, [["Professor", "Professor"], ["Associate Professor", "Associate Professor"], ["Senior Lecturer", "Senior Lecturer"], ["Assistant Professor", "Assistant Professor"]] %>
                <%= f.label :position, "Position" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Choose a password" %>
                <%= f.label :password, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: "Confirm your password" %>
                <%= f.label :password_confirmation, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@teacher.new_record? ? '<i class="material-icons right">arrow_forward</i>Sign up'.html_safe : '<i class="material-icons right">arrow_forward</i>Submit changes'.html_safe , class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/teachers/edit.html.erb
<%= render 'form' %>

app/views/teachers/my_courses.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">My Course Listing</h3>
  </div>
</div>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <% if logged_in? %>
            <% if current_user.courses.include?(course) %>
              <%= link_to "Remove", student_course_path(course_id: course.id), method: :delete %>
            <% else %>
              <%= link_to "Enroll", student_course_path(course_id: course.id), method: :post %>
            <% end %>
          <% end %>
          <%= link_to "Info", course_path(course) %>
          <% if teacher_logged_in? && course.teacher == current_teacher %>
            <%= link_to "Edit", edit_course_path(course) %>
            <%= link_to "Delete", course_path(course), method: :delete, data: {confirm: 'Are you sure?' } %> 
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if teacher_logged_in? %>
<div class="row">
  <div class="col s6 m6">
    <%= link_to "Create new course", new_course_path, class: 'waves-effect waves-light btn-large' %>
  </div>
</div>
<% end %>

app/views/teachers/my_students.html.erb
<% @courses.each do |course| %>
  <h3><%= course.name %></h3>
  <table>
    <thead>
      <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Grade</th>
          <th>Change grade</th>
          <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% course.students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.email %></td>
          <td><%= StudentCourse.where(student_id: student.id, course_id: course.id).first.grade %></td>
          <td>
            <%= form_tag(change_grade_path(student_id: student.id, course_id: course.id), id: 'grade-form') do %>
              <%= select_tag(:grade, options_for_select([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], 3), class: 'browser-default') %>
              <%= button_tag(class: "waves-effect waves-teal btn-flat" ) do %>
                <%= '<i class="material-icons">system_update_alt</i>'.html_safe %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to '<i class="material-icons left">email</i>'.html_safe, '#', class: "waves-effect waves-light btn-flat" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/teachers/new.html.erb
<%= render partial: 'shared/errors', locals: { obj: @teacher } %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @teacher.new_record? ? "Sign up!" : "Edit your profile!" %></h3>
        <div class="row">
          <%= form_for @teacher, html: {class: 'col s12'} do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                <%= f.label :name %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter your email address" %>
                <%= f.label :email, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.select :position, [["Professor", "Professor"], ["Associate Professor", "Associate Professor"], ["Senior Lecturer", "Senior Lecturer"], ["Assistant Professor", "Assistant Professor"]] %>
                <%= f.label :position, "Position" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Choose a password" %>
                <%= f.label :password, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: "Confirm your password" %>
                <%= f.label :password_confirmation, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@teacher.new_record? ? '<i class="material-icons right">arrow_forward</i>Sign up'.html_safe : '<i class="material-icons right">arrow_forward</i>Submit changes'.html_safe , class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<div class="row">
  <div class="col s6 m6">
    <div class="card blue-grey darken-1 sign-up-form">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= @teacher.name %></span>
        <p>Position: <%= @teacher.position %></p>
        <p>Email: <%= @teacher.email %></p>
      </div>
    </div>
    <% if current_teacher == @teacher %>
      <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_teacher_path(@teacher), class: "waves-effect waves-light btn" %>
    <% end %>
  </div>
</div>