config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :courses
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'student_course', to: 'student_courses#create'
  delete 'student_course', to: 'student_courses#destroy'
  post 'change_grade', to: 'student_courses#change_grade'
  resources :teachers, only: [:new, :create, :edit, :update, :show]
  get '/teachers/:id/my_courses', to: 'teachers#my_courses', as: 'teacher_courses'
  get '/teachers/:id/my_students', to: 'teachers#my_students', as: 'teacher_students'
  get 'teacher_login', to: 'teacher_sessions#new'
  post 'teacher_login', to: 'teacher_sessions#create'
  delete 'teacher_logout', to: 'teacher_sessions#destroy'
end

app/views/layouts/_dropdown.html.erb
<li><%= session_link %></li>
<% if logged_in? %>
  <li><%= link_to "profile", student_path(current_user) %></li>
<% end %>
<% if !logged_in? && !teacher_logged_in? %>
  <li class="divider"></li>
  <li><%= link_to "signup", new_student_path %></li>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development training</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2020 Tech University
    <%= link_to "Teacher's page", teacher_login_path, class: "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <%= render 'layouts/dropdown' %>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <%= render 'layouts/dropdown' %>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to "Tech University", root_path, class: "brand-logo right" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <%= render 'layouts/navlink' %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  <ul class="sidenav" id="mobile-demo">
    <%= render 'layouts/navlink' %>
    <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>
  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out-target">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/_navlink.html.erb
<li><%= link_to "Courses", root_path %></li>
<% if logged_in? %>
  <li><%= link_to "Students", students_path %></li>
  <li><%= link_to "My Page", student_path(current_user) %></li>
<% end %>
<% if teacher_logged_in? %>
  <li><%= link_to "My Courses", teacher_courses_path(current_teacher) %></li>
  <li><%= link_to "My Students", teacher_students_path(current_teacher) %></li>
  <li><%= link_to "My Page", teacher_path(current_teacher) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= yield %>    
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>